### PR TITLE
Improve GitHub Action workflow

### PR DESCRIPTION
**Pull request by koumaza**
* Change utility to uses from `curl` to` aria2`.
* Get release URI from the GitHub's API.
* Matrixed the GitHub actions workflows.

> * Update and rename build-zip.yml to build-zip.yaml
> * Update and rename release-zip.yml to release-zip.yaml
> * Update Makefile

I recommend purging Appveyor continuous-integration. (It fails.)

### CODE REVIEW

**Comment by yuk7** [comment]
I think this is not better way...

I think:
* don't use matrix build
* Setting the downloader from the argument of make
* don't use aria2 in makefile

**Comment by koumaza** [comment]
> I think this is not better way...
> 
> I think:
> 
> * don't use matrix build
> * Setting the downloader from the argument of make
> * don't use aria2 in makefile

I see, I fixed it now.
Please see its changes.

>I recommend purging Appveyor continuous-integration. (It fails.)
This is just my mistake. I would like you to forget it.

**Comment by yuk7** [comment]
aw, sorry
we can set aria2c from workflow file
like:
```
DLR=aria2c
DLR_FLAGS=-x16 -20
make -e
```

sorry bad english
I'll review it.
Thank you very much for your contribution!

**Comment by koumaza** [comment]
> aw, sorry
> we can set aria2c from workflow file
> like:
> 
> ```
> DLR=aria2c
> DLR_FLAGS=-x16 -20
> make -e
> ```
> 
> sorry bad english
> I'll review it.
> Thank you very much for your contribution!

Not your fault... I am sorry.

**Comment by koumaza** [comment]
> ```shell
> DLR=aria2c
> DLR_FLAGS=-x16 -20
> make -e
> ```

I adopted this and committed!

**Comment by koumaza** [comment]
Included some changes in 70908c1.
If there are features that you are not like, I'd like to tell me.

**Comment by yuk7** [comment]
No problem.
Thank you!

**Pull request merged**
